# storage_lights:
#   module: storage_lights
#   class: StorageLightsAutomation

# living_room_led_strips:
  # module: living_room_led_strips
  # class: LivingRoomLedStripsAutomation

ambient_lights_automation:
  module: ambient_lights
  class: AmbientLightsAutomation
  